//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trading_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ETradingDBEntities : DbContext
    {
        public ETradingDBEntities()
            : base("name=ETradingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<TopUp> TopUps { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    
        public virtual ObjectResult<GetNotificationsToday_Result> GetNotificationsToday()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotificationsToday_Result>("GetNotificationsToday");
        }
    
        public virtual ObjectResult<GetProductDetails_Result> GetProductDetails(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetails_Result>("GetProductDetails", productIDParameter);
        }
    
        public virtual ObjectResult<GetTopSellingProducts_Result> GetTopSellingProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopSellingProducts_Result>("GetTopSellingProducts");
        }
    
        public virtual ObjectResult<GetTopSellingProductsByVendor_Result> GetTopSellingProductsByVendor(Nullable<int> vendorID)
        {
            var vendorIDParameter = vendorID.HasValue ?
                new ObjectParameter("VendorID", vendorID) :
                new ObjectParameter("VendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopSellingProductsByVendor_Result>("GetTopSellingProductsByVendor", vendorIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetTotalSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetTotalSales");
        }
    
        public virtual ObjectResult<GetTotalSalesByDate_Result> GetTotalSalesByDate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalSalesByDate_Result>("GetTotalSalesByDate", dateParameter);
        }
    }
}
