//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trading_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string VendorCompanyPhoneNo { get; set; }
        public string VendorCompanyAddress { get; set; }
        public string VendorCompanyEmailID { get; set; }
        public string VendorCompanyName { get; set; }
        public Nullable<bool> VendorIsActive { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
